sudo: required

language: python 

services:
    - docker

before_install:
    - docker build -t btcrs/tiny-django

script:
    - docker run --rm -p 8000:8000 -v `pwd`/app:/code -w /code python app.py test 
    - docker ps -a
