sudo: required

language: python 

services:
    - docker

before_install:
    - docker build -t btcrs/tinydjango .

script:
    - docker run --rm -p 8000:8000 -v `pwd`/app:/code -w /code btcrs/tinydjango python app.py test 
    - docker ps -a

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push btcrs/tinydjango
